# Generated by Django 5.2.17 on 2026-08-28 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_user_auth_provider_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user.created', 'User created'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.deleted', 'User deleted'), ('role.granted', 'Role granted'), ('role.revoked', 'Role revoked')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('iam_users', 'Users'), ('iam_roles', 'Roles'), ('risk', 'Risk register'), ('controls', 'Controls'), ('audit', 'Audit findings'), ('incidents', 'Incidents'), ('obligations', 'Obligations')], max_length=32)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('assign', 'Assign')], max_length=16)),
                ('iso_clause', models.CharField(blank=True, max_length=16)),
                ('roles', models.ManyToManyField(blank=True, related_name='permissions', to='iam.role')),
            ],
            options={
                'ordering': ['resource', 'action'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'action'), name='unique_permission_resource_action')],
            },
        ),
    ]
