# Generated by Django 5.2.17 on 2026-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='entra_object_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Entra object ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_access_review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
