# Generated by Django 5.2.17 on 2026-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_user_department_user_entra_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamauditevent',
            name='event_type',
            field=models.CharField(choices=[('user.created', 'User created'), ('user.updated', 'User updated'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.deleted', 'User deleted'), ('role.granted', 'Role granted'), ('role.revoked', 'Role revoked')], max_length=32),
        ),
    ]
