# Generated by Django 5.2.17 on 2026-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_alter_iamauditevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Must change password at next login'),
        ),
    ]
