# Generated by Django 5.2.17 on 2026-08-31 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, verbose_name='MFA setup required'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Encrypted TOTP secret'),
        ),
        migrations.AlterField(
            model_name='iamauditevent',
            name='event_type',
            field=models.CharField(choices=[('user.created', 'User created'), ('user.updated', 'User updated'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.deleted', 'User deleted'), ('role.granted', 'Role granted'), ('role.revoked', 'Role revoked'), ('mfa.enabled', 'MFA enabled'), ('mfa.disabled', 'MFA disabled'), ('mfa.reset', 'MFA reset by admin')], max_length=32),
        ),
        migrations.CreateModel(
            name='MfaRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
