# Generated by Django 5.2.17 on 2026-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamauditevent',
            name='event_type',
            field=models.CharField(choices=[('user.created', 'User created'), ('user.updated', 'User updated'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('user.deleted', 'User deleted'), ('role.granted', 'Role granted'), ('role.revoked', 'Role revoked'), ('permission.granted', 'Permission granted'), ('permission.revoked', 'Permission revoked'), ('mfa.enabled', 'MFA enabled'), ('mfa.disabled', 'MFA disabled'), ('mfa.reset', 'MFA reset by admin'), ('mfa.codes_regenerated', 'MFA recovery codes regenerated'), ('profile.updated', 'Profile updated by the account holder'), ('password.reset_requested', 'Password reset requested by admin')], max_length=32),
        ),
    ]
