# Generated by Django 5.2.17 on 2026-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0013_alter_iamauditevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
