# Generated by Django 5.2.17 on 2026-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('in_scope', models.BooleanField(default=True)),
                ('implementation_status', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('partial', 'Partial'), ('implemented', 'Implemented'), ('not_applicable', 'Not Applicable')], default='not_implemented', max_length=32)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
