# Generated by Django 5.2.17 on 2026-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('next_review_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
