# Generated by Django 5.2.17 on 2026-08-31 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='notification key')),
                ('signature', models.CharField(blank=True, default='', max_length=128, verbose_name='state when cleared')),
                ('dismissed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_notification_dismissal_per_user')],
            },
        ),
    ]
