# Generated by Django 5.2.17 on 2026-09-04 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='Acentria', help_text='Organisation this platform governs. Used in the emails the platform sends.', max_length=128)),
                ('primary_contact_email', models.EmailField(blank=True, default='', help_text='Where users are told to turn for access problems.', max_length=254)),
                ('allowed_login_domain', models.CharField(blank=True, default='', help_text='Email domain an account must belong to in order to sign in. Leave blank to keep using the ALLOWED_LOGIN_DOMAIN environment value.', max_length=253)),
                ('require_mfa_for_all_users', models.BooleanField(default=False, help_text='Every account without MFA is asked to enroll at its next sign-in and cannot use the platform until it does (A.8.5).', verbose_name='require MFA for all users')),
                ('session_expiry_minutes', models.PositiveIntegerField(default=480, help_text='How long a sign-in stays valid before the user must authenticate again.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10080)])),
                ('password_min_length', models.PositiveSmallIntegerField(default=12, help_text='Minimum characters for a new password (A.5.17).', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(128)])),
                ('access_review_interval_days', models.PositiveSmallIntegerField(default=90, help_text="How far ahead a new account's first access recertification is scheduled (A.5.18).", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('audit_log_retention_days', models.PositiveSmallIntegerField(default=365, help_text='How long IAM audit events and sign-in attempts are kept before `purge_audit_log` deletes them (A.8.15).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3650)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
